# Generated by Django 4.0.3 on 2022-04-10 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=150, verbose_name='Source')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getJsonData.country', verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Datetime')),
                ('data', models.CharField(max_length=200, verbose_name='Data')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getJsonData.source', verbose_name='Source')),
            ],
        ),
    ]
