# Generated by Django 4.0.3 on 2022-04-24 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getJsonData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NasdaqJOHNMATTPALL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('hong_kong_8_30', models.FloatField(null=True)),
                ('hong_kong_14_00', models.FloatField(null=True)),
                ('london_09_00', models.FloatField(null=True)),
                ('new_york_9_30', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NasdaqJOHNMATTPLAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('hong_kong_8_30', models.FloatField(null=True)),
                ('hong_kong_14_00', models.FloatField(null=True)),
                ('london_09_00', models.FloatField(null=True)),
                ('new_york_9_30', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NasdaqODAPALUMUSD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='NasdaqODAPCOPPUSD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='NasdaqODAPNICKUSD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('value', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NasdaqSHFERBV2013',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('pre_settle', models.FloatField(null=True)),
                ('open', models.FloatField(null=True)),
                ('high', models.FloatField(null=True)),
                ('low', models.FloatField(null=True)),
                ('close', models.FloatField(null=True)),
                ('settle', models.FloatField(null=True)),
                ('ch1', models.FloatField(null=True)),
                ('ch2', models.FloatField(null=True)),
                ('volume', models.FloatField(null=True)),
                ('prev', models.FloatField(null=True)),
                ('change', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=150, verbose_name='Document Type')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getJsonData.area', verbose_name='Area')),
            ],
        ),
        migrations.CreateModel(
            name='DayAheadPriceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Datetime')),
                ('data', models.CharField(max_length=200, verbose_name='Data')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getJsonData.documenttype', verbose_name='Document Type')),
            ],
        ),
    ]
